### PR TITLE
Multi-monitor support improvements.  Deprecates `Make topbar follow monitor focus`

### LINKED ISSUE #519: Gnome 44: windows on primary monitor resize to overlap top bar
**Describe the bug**

I'm running the gnome-44 support branch on Fedora 38. When I have one or more windows open on my primary monitor, then switch to my secondary monitor and back, the windows on the primary monitor resize to full height, appearing under the top bar. The only way I've seen to get them back to normal is to open another window on the primary monitor. Possibly noteworthy: while the secondary monitor is focused, the windows on the primary monitor leave space for the top bar, even though it does not appear.

**To Reproduce**
1. Open one or two windows on the primary monitor.
2. Switch to secondary monitor with mouse or keyboard
3. Switch back to primary monitor with mouse or keyboard (it is not necessary to create a window on the secondary monitor.

**Expected behavior**

**Screenshots**
To be added later, if the description is not clear enough.

**System information:**
```
Distribution: Fedora Linux
GNOME Shell 44.1
Display server: Wayland
PaperWM branch/tag: fixes-gnome-44-support
PaperWM commit: 47a6d9ead03c899a96cf5efe57d7b747a74db262
Enabled extensions:
- appindicatorsupport@rgcjonas.gmail.com
- gnome-extension-brightness@bruno.englert.gitlab.com
- paperwm@hedning:matrix.org
- user-theme@gnome-shell-extensions.gcampax.github.com


```

Edited to add:

Turning off the "Make top bar follow monitor focus" prevents this from happening. With "Enable window position bar" turned on, they may briefly expand to full screen height, but then quickly return to the correct height.

### PR DESCRIPTION
**Pull request by jtaala**
Fixes #519.

This PR addresses several issues as discussed in #519.  Namely, it:

1. deprecates the `Make topbar follow monitor focus` functionality: this is quite broken and has been for some time. 
 It's not supported on Gnome (e.g. dynamically changing topbar monitor with mouse focus) and the code implemented in PaperWM to support this is quite "hacky" - in short I don't think this should be supported by PaperWM.  It's enabled by default, and often causes confusion for users as it is prone to causing visual and window layout issues on multi-monitor setups;

2. improves multi-monitor support.  Fixes several bugs relating to changing monitor configurations and/or changing the primary display.  These changes allow PaperWM to correctly reconfigure window layouts and topbar configuration when monitor setup changes.

This should provide a simplified and improved multi-monitor experience, while also making PaperWM's codebase cleaner and a easier to maintain.  I'd like to improve multi-monitor usability moving forward on PaperWM and these changes put us in a better position to do so.

### CODE REVIEW

**Comment by Lythenas** [comment]
I have been testing this and it works without issues. But are we sure no-one is relying on the "Make topbar follow monitor focus"? I know it is less important now that we have a (fake) topbar on all monitors anyway.

 would be inclined to approve it, but I also didn't use the "Make topbar follow monitor focus".

**Comment by jtaala** [comment]
> I have been testing this and it works without issues. But are we sure no-one is relying on the "Make topbar follow monitor focus"? I know it is less important now that we have a (fake) topbar on all monitors anyway.
> 
> would be inclined to approve it, but I also didn't use the "Make topbar follow monitor focus".

Thanks @Lythenas.

I've had #519 up for a few weeks hoping to get some feedback there, haven't had any suggesting it's a needed feature (including the OP).  I've made the title for this PR pretty explicit re deprecating it hoping to get feedback here too.

Currently I don't believe anyone would be using with functionality _without_ the (fake) topbar also enabled - that scenario is currently broken.

I guess it's a weigh-up of that vs. the feature stopping / impeding fixing and improving multi-monitor support (including looking to address the tiled-windows in overview mode issues etc.).

**Review by Lythenas — APPROVED** [review]

**Comment by Lythenas** [comment]
We can also wait a bit longer, but if the current behavior is broken without the (fake) topbar on all monitors, I think we can just remove it.

**Comment by jtaala** [comment]
> We can also wait a bit longer

Yep, happy to wait longer for any feedback or other points of view.

**Comment by theol0403** [comment]
Not sure if it would be better for me to provide more information, but when checking out and installing this branch, the 2nd monitor didn't seem to work at all - windows would not scroll, tile, or snap. Additionally, scrolling windows on the primary monitor would get "stuck" on the other monitor and become some strange half-scratch half-tiled window. 

If you are unable to easily reproduce this I am happy to sit down and provide a more detailed report.

**Comment by jtaala** [comment]
> Not sure if it would be better for me to provide more information, but when checking out and installing this branch, the 2nd monitor didn't seem to work at all - windows would not scroll, tile, or snap. Additionally, scrolling windows on the primary monitor would get "stuck" on the other monitor and become some strange half-scratch half-tiled window.
> 
> If you are unable to easily reproduce this I am happy to sit down and provide a more detailed report.

Oh dear, okay, first up can you please run the `gather-system-info.sh` script and paste the output here?

Thanks for testing and letting us know!

**Comment by jtaala** [comment]
Just merged in latest `develop` into this PR branch too, so maybe do a:

```
git checkout deprecate-topbar-follow-focus
git pull
```

and logout/login again as well.

**Comment by theol0403** [comment]
Apologies for the delay, I'm not sure if the merge or some other factor changed something, and I have been unable to reproduce after a couple of minutes of testing. Will use it for a full work day and report back.

Thanks for all the great work!

**Comment by jtaala** [comment]
> Will use it for a full work day and report back

Hey @theol0403 - just checking that you haven't seen the multi-monitor issue you mentioned.

**Comment by theol0403** [comment]
> > Will use it for a full work day and report back
> 
> Hey @theol0403 - just checking that you haven't seen the multi-monitor issue you mentioned.

Hey, no bugs found! Sorry for the false alarm - this PR actually seems to reduce the number of bugs/desyncs I've encountered in the last day. Thanks! 

I'll make a new issue if I ever encounter it again.

**Comment by Lythenas** [comment]
I've also been using this for a couple of days without any issues now.

**Pull request merged**
