### PR TITLE
Add keybindings to switch to ws from all monitors

### LINKED ISSUE #635: Switch to a workspace sticked to another monitor
**Is your feature request related to a problem? Please describe.**
I have 2 monitors setup and somehow all workspaces are moved to my right monitor. And there are no workspaces on the left monitor at all.
Is there a way to move (not swap) workspaces from one monitor to another?

**Describe the solution you'd like**
Have a shortcut to **move** a workspace to a specific monitor.
Or make optional sticking a workspace to a monitor.

It is also interesting in what way the workspaces distributed between monitors by default (say if I have 5 workspaces and 2 monitors)?
I see that when a workspace has no windows I can switch to it from any monitor but once there is at least one window in a workspace the workspace sticks to one specific monitor, is this expected behavior? 
Would it possible to make this optional maybe?

### PR DESCRIPTION
**Pull request by Lythenas**
Gnome 44 port of #645

> Fixes #635
> 
> Adds two new keybindings:
> 
>     Switch to workspace below (ws from all monitors)
>     Switch to workspace above (ws from all monitors)
> 
> by default they have no keys bound.
> 
> They work the same as "Switch to workspace below/above (ws only from current monitor)" (renamed from just "Switch to workspace below/above"). Except the user can switch to all workspaces (except the once currently active on another monitor).
> 
> Please test this.

### CODE REVIEW

**Comment by Lythenas** [comment]
@jtaala btw during testing I noticed that the workspace indicator on the secondary display looked strange. But I don't think this has anything to do with this PR.

Screenshot from 2023-11-12 12-59-48

**Comment by jtaala** [comment]
> @jtaala btw during testing I noticed that the workspace indicator on the secondary display looked strange. But I don't think this has anything to do with this PR.
> 
> Screenshot from 2023-11-12 12-59-48

Thanks @Lythenas.  I'm trying to find the issue where something similar was mentioned when using custom styles (so might not be like here) and using workspace colours (not the default gnome shell background).

**Review by jtaala — APPROVED** [review]
Looks good to me.  Tested and appears to work well!

Nice job!

**Comment by jtaala** [comment]
Hey @Lythenas have approved.  Feel free to merge when ready.

**Comment by jtaala** [comment]
> > @jtaala btw during testing I noticed that the workspace indicator on the secondary display looked strange. But I don't think this has anything to do with this PR.
> > Screenshot from 2023-11-12 12-59-48
> 
> Thanks @Lythenas. I'm trying to find the issue where something similar was mentioned when using custom styles (so might not be like here) and using workspace colours (not the default gnome shell background).

You appear to be using custom styling? (just looks like it since the window selection is an orange colour instead of the default blue).  If so, can you share the styling?  or might it be another extension (like blur-my-shell or just-perfection etc.?).

**Comment by Lythenas** [comment]
@jtaala I can't merge. So feel free to merge yourself. It says:

> The base branch restricts merging to authorized users

Regarding your question: I can't find a user.css in the VM where I tested. Also no other extension is enabled, only PaperWM and Ubuntu AppIndicators. I think I just changed the color in the gnome settings (but maybe it was the default):

Screenshot from 2023-11-13 18-00-40

**Comment by jtaala** [comment]
> @jtaala I can't merge. So feel free to merge yourself. It says:
> 
> > The base branch restricts merging to authorized users

No dang it - I fixed this (but for develop branch) - forgot about gnome branches.

**Comment by jtaala** [comment]
Okay, *should* have fixed it for gnome branches.  I'll merge anyways.

**Pull request merged**
