### PR TITLE
Adds user configurable tiling edge margins to PaperWM extension settings ui

### PR DESCRIPTION
**Pull request by jtaala**
Closes #364 

This PR adds user configurable tiling edge margins to the settings ui.  Edge margins are the minimum margin from screen edges to the leftmost and rightmost window edges.  Currently the edge margin is set to 0px (by design).

Edge margins were discussed in #364, with some users preferring having an edge margin.  This PR allows users to:

- select their preferred margins;
- preview the edge margins as the settings is changed;

### Video demonstration of changing edge margins:

https://user-images.githubusercontent.com/30424662/213923583-ffa15624-4ce0-419b-a31c-34dabf53959d.mp4

_NOTE: this PR has been implemented in the [PaperWM-redux](https://github.com/PaperWM-redux/PaperWM) fork, which you can install if you want this, or any of [my other open PRs](https://github.com/paperwm/PaperWM/pulls/jtaala)._

### CODE REVIEW

**Comment by jtaala** [comment]
Hey @hedning, this was a while back but you responded regarding the design decisions re edge margins back in #364  - keen to get any thoughts re this PR which makes them user configurable.

**Comment by jtaala** [comment]
@smichel17 - given our conversation in [#454](https://github.com/paperwm/PaperWM/pull/454) and [#456](https://github.com/paperwm/PaperWM/pull/456) re user settings - what do you think of this one?

I think this one definitely fits - as it's a margin. 

Also, interestingly I've noticed that it's one of the first things that seems "off" to new users, although it's intended behaviour to let users know when they are a tiling edge.  I prefer `5px` though - so I can see my nicely styled border but still see when at the tiling edge.

Anyways, we could leave this one there and move or remove the `Useful window widths/heights` settings to cleanup it up a bit (removing the widths/heights setting and users can use dconf to set those ones).

**Comment by smichel17** [comment]
I think this is one we can fix without a setting. I'll reply in #364

**Comment by jtaala** [comment]
> I think this is one we can fix without a setting. I'll reply in #364

Thanks @smichel17!  I don't think it's a bug though, it's a feature! :-).  I added a comment to #364 outlining why I chose to have it as a simple user-defined preference setting (which is fit nicely in the settings ui with the margin settings).

**Comment by Lythenas** [comment]
I tested this and it seems to work without issues. I set the margin to 5px and I also have the other margins set to 5px. So there is no space between the borders and the edge of the screen.

**Comment by jtaala** [comment]
As mentioned in #488, closing this in favour of #488.

**Pull request closed without merging**
