### PR TITLE
Fix 637 add support for dynamic / animated wallpapers (gnome 45)

### LINKED ISSUE #637: Dynamic Wallpapers doesn't works with PaperWM
**Describe the bug**

**To Reproduce**
1. Install Any Dynamic Wallpaper.
2. Set the wallpaper in gnome-settings
3. Activate PaperWM
4. The background becomes flat color.

**Expected behavior**
The background should be same as when the extension was disabled.

**Screenshots**
Screenshot from 2023-10-18 00-41-37
image
image

**System information:**
Distribution: Fedora Linux
GNOME Shell 45.0
Display server: Wayland
PaperWM branch/tag: release
PaperWM commit: 7919f129bb8027e86ad8f54db682c57340bf5fd0
Enabled extensions:
- AlphabeticalAppGrid@stuarthayhurst
- Battery-Health-Charging@maniacx.github.com
- burn-my-windows@schneegans.github.com
- clipman@popov895.ukr.net
- cloudflare-warp-toggle@khaled.is-a.dev
- color-picker@tuberry
- hotedge@jonathan.jdoda.ca
- supergfxctl-gex@asus-linux.org
- quake-terminal@diegodario88.github.io
- unsafe-mode-menu@linushdot.local
- grand-theft-focus@zalckos.github.com
- miniview@thesecretaryofwar.com
- background-logo@fedorahosted.org
- appindicatorsupport@rgcjonas.gmail.com
- auto-move-windows@gnome-shell-extensions.gcampax.github.com
- user-theme@gnome-shell-extensions.gcampax.github.com
- blur-my-shell@aunetx

**Additional context**
It works as expected when using the normal backgrounds.

### PR DESCRIPTION
**Pull request by jtaala**
Fixes #637 by adding support for Gnome animated / dynamic wallpapers.

### CODE REVIEW

**Comment by Thesola10** [comment]
Just testing, but are wallapers provided by [Nostalgia](https://flathub.org/fr/apps/im.bernard.Nostalgia) dynamic walls? I only have night/day walls on my system otherwise since dynamic wallpapers are deprecated, but those work fine in my testing.

**Comment by Thesola10** [comment]
Looks like [it's the case](https://gitlab.gnome.org/bertob/nostalgia/-/tree/master/data/wallpapers/41?ref_type=heads) seeing as they have morning variants as well.

**Review by Thesola10 — APPROVED** [review]

**Comment by jtaala** [comment]
Not sure re those ones - I used the ones from [iitzrohan](https://github.com/iitzrohan) link:

https://github.com/paperwm/PaperWM/issues/637#issuecomment-1768161824

I like the fuji one.

**Comment by Thesola10** [comment]
yep, just tested, those work too (and don't work without the PR)

my favorite is the Magical Index one

**Comment by jtaala** [comment]
Switching back to a standard wallpaper seems it gets a bit confused sometimes.  Will try to reproduce and fix that and then merge this in.

**Comment by Thesola10** [comment]
ah, yep, can see it now, sometimes it switches back to the dynamic wallpaper

**Comment by jtaala** [comment]
yeah, it's still live - need to figure out how to kill it when loading an image.  I'll figure it out.

**Comment by jtaala** [comment]
Hey @Thesola10,

I believe I've now solved the switching back issue (now we're creating a new `Background` instance (which destroys any animated one) when updating/switching backgrounds.

Could you give this a test.  I'm running this now and it's working well.

Jay.

**Review by Thesola10 — APPROVED** [review]
Gave it a test, switching between dynamic and night/day works perfectly now, thanks

**Pull request merged**
