### PR TITLE
Added switch-global-* actions

### PR DESCRIPTION
**Pull request by dawsers**
This pull request is to add four new actions that complement `switch-right`, `switch-left`, `switch-up` and `switch-down` with *global* versions that change window regardless of monitor boundaries. This means the action will not respect the current monitor boundaries and will select a window on the adjacent monitor if the previous selection was at a boundary. For example, `switch-global-right` when the selected window is the rightmost of a *space* will move to the monitor on the right and select the first window. While within monitor boundaries, the behavior is exactly the same as `switch-*`.

1. It doesn't change other actions, you can always keep on changing monitors with `<Super><Shift><right/left/up/down>`, which preserves the last selected window on each *space* when moving back and forth, while `switch-global-*` actions don't (they move to the *"closest"* window).
2. There are no default key bindings for these actions. For example, I have replaced the ones for `switch-*` with the actions `switch-global-*`, but by default, the change doesn't do anything.

The pull request is backwards compatible, transparent, and needs the user to enable the behavior knowingly; it doesn't add any key bindings by default.

### CODE REVIEW

**Comment by jtaala** [comment]
Thanks for the PR @dawsers!

Looks okay to me.  I'll give this a test soon.

_Note: I changed the branch to `develop` since we don't accept PRs directly into `release` branch._

**Comment by jtaala** [comment]
@kassick looks like the `rebase-pr` action failed here.  Weirdly, looks like a CORS issue trying to add a comment - not sure what's going on there.  I just changed it to `develop` branch manually.

**Comment by jtaala** [comment]
Hey @dawsers.  Looks good.  I've just implemented fluid minimap/navigation across monitors (i.e. the minimap jumps to the other monitor - feels better and more natural here).  Also applied paperwm linter (which just fixed up some things re style/formatting).

**Review by jtaala — APPROVED** [review]
Looks and feels good.  I like this approach - glad you thought of it!

**Comment by jtaala** [comment]
@dawsers - see https://github.com/paperwm/PaperWM/discussions/723#discussioncomment-8290949

Given your contribution, if you have a donation link to accept donations (e.g. buymeacoffee.com etc) let me know and I'll add for the next release.

**Comment by dawsers** [comment]
Thank you so much for cleaning it up and adding it!

There is no need to add me to donations or anything. I have been using PaperWM just for a few days (moved from QTile), and I really like it, so I am very grateful to you guys.

I guess this PR can be closed.

**Comment by jtaala** [comment]
I'll merge this into `develop` and add this to the next release (which I'll likely do in the next few days).  Thanks for contributing @dawsers!

**Comment by Thesola10** [comment]
> @kassick looks like the `rebase-pr` action failed here. Weirdly, looks like a CORS issue trying to add a comment - not sure what's going on there. I just changed it to `develop` branch manually.

may have something to do with [permissions](https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac) somehow? maybe due to committer not being a trusted contributor

**Pull request merged**
