### PR TITLE
Gnome 46 compatibility

### LINKED ISSUE #782: Gnome 46 testing issues
**Describe the bug**

```
Extension paperwm@paperwm.github.com: TypeError: MessageTray.SystemNotificationSource is not a constructor

Stack trace:
  notify@file:///usr/share/gnome-shell/extensions/paperwm@paperwm.github.com/extension.js:212:22
  errorNotification@file:///usr/share/gnome-shell/extensions/paperwm@paperwm.github.com/extension.js:232:35
  enableUserConfig@file:///usr/share/gnome-shell/extensions/paperwm@paperwm.github.com/extension.js:162:22
  enable@file:///usr/share/gnome-shell/extensions/paperwm@paperwm.github.com/extension.js:61:14
  _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:263:38
  async*_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:621:24
  _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:726:18
  createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730:46
  enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:286:29
  EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:453:38
  _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329:38
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  @resource:///org/gnome/shell/ui/init.js:21:20
  ```

**To Reproduce**

try to load the extension in gnome 46

```
Example:
Distribution: openSUSE Tumbleweed + GNOME:Next
GNOME Shell 46.beta
PaperWM branch/tag: 45.9.1
PaperWM commit: 45.9.1
Enabled extensions:
- paperwm@paperwm.github.com
- trayIconsReloaded@selfmade.pl
- user-theme@gnome-shell-extensions.gcampax.github.com
```

### LINKED ISSUE #805: Switching windows with shortcuts `Super+h/l` leads to an automatic infinitive keypressing of `h/l`
**Describe the bug**
When I press `Super+l` and switch to the right of the current, the target window gets focused and receives infinitive keypressing of `l`. It happens only to a few applications (e.g., kitty terminal with x11 backend, goldendict).

**To Reproduce**
1. Run kitty terminal in wayland by: `kitty -c NONE -o linux_display_server=x11`.
2. Switch left or right to kitty's window by `Super+h/l`.
3. Release `h/l` while holding `Super`, and kitty will receives infinitive `h/l` until `Super` is released and `h/l` is pressed again in kitty.

**Expected behavior**
The target window should not receive infinitive keypressing.

**Screenshots**
image

**System information:**

```
Distribution: Arch Linux
GNOME Shell 46.0
Display server: Wayland
PaperWM branch/tag: develop
PaperWM commit: 33881025b8804ba22459c657239035d69a0ec4f3
Enabled extensions:
- appindicatorsupport@rgcjonas.gmail.com
- user-theme@gnome-shell-extensions.gcampax.github.com
- Bluetooth-Battery-Meter@maniacx.github.com
- AlphabeticalAppGrid@stuarthayhurst
- kimpanel@kde.org
- runcat@kolesnikov.se
- blur-my-shell@aunetx
- gnome-ui-tune@itstime.tech
- unite@hardpixel.eu
- paperwm@paperwm.github.com
```

**Additional context**
1. It seems that it only happens to xwayland backend windows, but I'm not 100% sure.
2. I believe it's not PaperWM's fault, but I wonder if there could be some solutions.

Currently my workaround for this problem is to comment out this line in file `tiling.js`, function `updateSelection`:
```js
    // ensure window is properly activated (if not activated)
    if (space === spaces.activeSpace) {
        if (metaWindow !== display.focus_window) {
            // Main.activateWindow(metaWindow);
        }
    }
```
This is not an elegant solution since it disables window focus during switching, which makes the window gray through all the switching process.
I suggest that the selected window should be highlighted just like that in *Live Alt Tab*, but I'm afraid I cannot figure it out.

### PR DESCRIPTION
**Pull request by jtaala**
This PR adds Gnome 46 compatibility.

Main issue is that Gnome 46 `MessageTray` and `notification` implementation has changed.

This PR simplifies PaperWM notification approach to use the supported extension notification system.

Doing this makes PaperWM compatible with Gnome 45 & 46.

Note: there may be other Gnome 46 specific issues I haven't found yet.

### CODE REVIEW

**Comment by jtaala** [comment]
I'm seeing some keybinds being passed through to the actors in Gnome 46.  Still trying to find out what's changed and what's going on with that.  Currently stopping this PR from being released.

**Comment by Plyply99** [comment]
> I'm seeing some keybinds being passed through to the actors in Gnome 46. Still trying to find out what's changed and what's going on with that. Currently stopping this PR from being released.

I think that is what is happening when I use the app Freetube. When a video is playing and I switch to the app it causes the video to skip.  I think the switch left or right keybind is being passed to the video player.

**Comment by jtaala** [comment]
> > I'm seeing some keybinds being passed through to the actors in Gnome 46. Still trying to find out what's changed and what's going on with that. Currently stopping this PR from being released.
> 
> I think that is what is happening when I use the app Freetube. When a video is playing and I switch to the app it causes the video to skip. I think the switch left or right keybind is being passed to the video player.

This would be it.  There's definitely something changed with `pushModal`, `popModal` implementations in Gnome 46.  I've found a workaround but we lose the mini-map (or the ability to detect `key-release-event`s to close the mini-map. 
 Still working on it, but may need to rewrite the keybind system.

**Comment by Plyply99** [comment]
Just tried the new commits. Seems to be working well now. No issues in my video player.

**Comment by jtaala** [comment]
All, appreciate you could test out the latest commit on this branch.  Ready to release this asap.

**Comment by Plyply99** [comment]
The shading is working also. Very nice.

**Comment by amfern** [comment]
Tested this branch too. Can confirm it work :+1:

**Pull request merged**
