### PR TITLE
Improve scratch window behaviours (for mouse-dragging windows and new windows when a scratch window is selected)

### PR DESCRIPTION
**Pull request by jtaala**
This PR changes several widow behaviours related to scratch windows.  It seeks to make scratch windows more predictable (in how one scratches a window) and try to minimise instances of "accidentally/unexpectedly" scratching windows.

Users (especially new users) seem to struggle with some of the behaviours for scratch windows.

See some example comments here:

- https://github.com/paperwm/PaperWM/issues/680#issuecomment-1806929052
- https://github.com/paperwm/PaperWM/issues/700#issue-1997608259
- https://github.com/paperwm/PaperWM/issues/700#issuecomment-1824202077

On review, a couple of behaviours are rather unintuitive with scratch windows:

1. when a scratch window is selected, any new window opened will also be scratched.  I understand the thought here, but this is rarely what's wanted (for me anyway) and often leads to confusion.  This PR undoes this.  New windows will be tiled (regardless of whether a scratch window is currently selected).

2. Dragging a window (with mouse) and NOT dropping on a target now re-tiles that window (previously it scratched that window).  I've had two user reports in the last few weeks of this (reported as a bug).  In any case, it seems the more intuitive option of for that window to be re-tiled:

https://github.com/paperwm/PaperWM/assets/30424662/9c4a20d6-52e3-408f-9c0a-62ee0ceb6244

### CODE REVIEW

**Comment by Lythenas** [comment]
Is it possible to somehow keep the highlight where the window will be tiled when you let it go? I think that would make it more obvious what is going to happen.

**Comment by jtaala** [comment]
Sorry for all the review requests @Lythenas!

**Comment by jtaala** [comment]
> Is it possible to somehow keep the highlight where the window will be tiled when you let it go? I think that would make it more obvious what is going to happen.

Hmm - I don't think so (not without a large rewrite I think).  Currently when a user let's go we're simply `unmakeScratchWindow` - so there's no guarantee it would get tiled in the last highlight area.  It's kind of like just unscratching an already scratched window (it'll jump back into some tiling spot).

**Comment by jtaala** [comment]
I'll have a bit more of a play around - maybe I can keep the last highlight active (until another one is selected).

**Comment by Lythenas** [comment]
Alternatively maybe making the highlight "triggers" bigger, so there is always a highlight would be better. But not sure how exactly that would interact between vertical and horizontal highlights. I rarely ever use the columns feature. So it might be a bit tricky to get it to feel like it does what you want it to do.

**Comment by jtaala** [comment]
@Lythenas, give the latest a go.  We keep the last drop target active now.  Feels visually more intuitive.

**Comment by Lythenas** [comment]
Yes that feels much better and is much more intuitive I think. I'm fine with merging this.

**Review by Lythenas — APPROVED** [review]

**Pull request merged**
