### PR TITLE
Update broken link, correct typos

### PR DESCRIPTION
**Pull request by AndrewKvalheim**
Just trying PaperWM today—thanks!—and noticed a broken link in the readme. Then when I opened it for editing I spotted a few typos too.

### CODE REVIEW

**Comment by Lythenas** [comment]
The changes seem fine. Thanks for creating a PR.

For the schema changes I'm not sure if you need to regenerate it when you change the summary only or if that is not needed. @jtaala do you know?

Also it seems the github check is broken :(

**Comment by jtaala** [comment]
> For the schema changes I'm not sure if you need to regenerate it when you change the summary only or if that is not needed. @jtaala do you know?

Hey @Lythenas - no, not for the summary / description stuff.  Binary compile is just if actual value or non-description schema properties change.

**Comment by jtaala** [comment]
> Just trying PaperWM today—thanks!—and noticed a broken link in the readme. Then when I opened it for editing I spotted a few typos too.

Thanks @AndrewKvalheim!  apparently I need a better spell-check! (which is just currently my brain...).

**Comment by jtaala** [comment]
I'll wrap this into the next release as well.

**Pull request merged**
