### PR TITLE
FIX overview to correctly animate to out of view window following overview "hiding" event

### LINKED ISSUE #347: Animations glitch on overview
Happening since updating to gnome 3.38.
OS: Fedora 33
Using latest release.

### PR DESCRIPTION
**Pull request by jtaala**
Fixes #347. 

This PR fixes a long-standing issue where after selecting a window in overview, does not correctly animate (shows no animation) to the selected window if it is outside current viewport.

Internally, `focus_handler` was not respecting overview (it was attempting to ensureViewport when overview was shown).  This PR fixes this and ensures that if a window is selected (in overview), then the animation (moving viewport to selected window) is executed on that window _after_ overview "hidden" event.

### current (broken) animation:
https://user-images.githubusercontent.com/30424662/228481112-ce701eaf-04e1-4e56-82ac-6f627d9448a2.mp4

### this PR animation (fixed):
https://user-images.githubusercontent.com/30424662/229046333-2aa11748-bc12-4f75-99ff-d41b959f1ebf.mp4

_NOTE: this PR has been implemented in the [PaperWM-redux](https://github.com/PaperWM-redux/PaperWM) fork, which you can install if you want this, or any of [my PRs](https://github.com/paperwm/PaperWM/pulls/jtaala) that are open._

### CODE REVIEW

**Comment by paradajz** [comment]
You have no idea how much this PR makes me happy! :D It works great.

**Comment by jtaala** [comment]
> You have no idea how much this PR makes me happy! :D It works great.

Lol, I think I do now - thinking about it, maybe part of the reason I didn't use overview much was because that snapping was jarring (and was harsh on my paperwm buzz).

**Comment by jtaala** [comment]
Hey all (and @paradajz) - please note I fixed a bug in this PR that can occur when restarting / first logging in (was due to not defining the default values for `force` and `moveto` option parameters).

Just a heads-up, you might want to pull the latest if you're using this.

Thanks!

**Comment by Lythenas** [comment]
This seems to work fine.

However do we even want to show the animation (after the overview closes)? Or do we just want to be at the correct location when the overview closes? (if that is possible)

I'm fine with either as I don't really use the overview anyway.

**Comment by jtaala** [comment]
> This seems to work fine.
> 
> However do we even want to show the animation (after the overview closes)? Or do we just want to be at the correct location when the overview closes? (if that is possible)
> 
> I'm fine with either as I don't really use the overview anyway.

I'd say the former feels good/natural to me, e.g. windows are placed where they were, and we move as if normally selecting a window out of view.  Trying the other way might be possible, but would require clone position manipulation while in overview (maybe).

**Review by Lythenas — APPROVED** [review]

**Pull request merged**
