### PR TITLE
Backport of improve-gnome-pill-behaviour from gnome-45 (improves animations / some visuals)

### PR DESCRIPTION
**Pull request by jtaala**
This PR is a backport PR for gnome 44-42 from #624.

It aligns with improvements in the gnome-45 latest version (release v45.1.1).

### CODE REVIEW

**Comment by jtaala** [comment]
@Lythenas - if you're still on 44 (or 42-43) are you able test this one?  Arch has moved over to 45 it looks like, which means I can't test natively (have tested in a gnome 44 vm though).

**Comment by Lythenas** [comment]
I found this^^
[Screencast from 12.10.2023 13:28:57.webm](https://github.com/paperwm/PaperWM/assets/32217236/a98667ab-c489-423f-a127-5fdfe43d4cb3)

```
Distribution: Ubuntu
GNOME Shell 42.9
Display server: Wayland
PaperWM branch/tag: improve-gnome-pill-behaviours-backport
PaperWM commit: b6b62c4cfbf70f45e5523f01aab74d1e0deb887b
Enabled extensions:
- paperwm@paperwm.github.com
- search-light@icedman.github.com
- tophat@fflewddur.github.io
- arch-update@RaphaelRochet
- date-menu-formatter@marcinjakubowski.github.com
- expandable-notifications@kaan.g.inam.org
- lockkeys@vaina.lt
- ubuntu-appindicators@ubuntu.com
```

Besides that I see no problems. Although I'm also not sure 100% what animations were fixed.

Edit: I notices the screencast was a bit laggy. I'm just moving my cursor between monitors and every time it triggers the animation. After the animation everything (also with windows) seems to be back to normal.

**Comment by jtaala** [comment]
Thanks for testing and finding that @Lythenas!

**Comment by jtaala** [comment]
Hey @Lythenas,

I've just pushed up a fix for the animation triggering when moving mouse to different monitors.

Could you do another test when you can and let me know that the issue is resolved.

Cheers,

Jay.

**Review by Lythenas — APPROVED** [review]
Works fine now, thanks.

**Pull request merged**
