### PR TITLE
Add section about incompatible extensions to readme

### PR DESCRIPTION
**Pull request by Lythenas**
Related to #784 

Add a section to the readme to list incompatible extensions.

### CODE REVIEW

**Comment by Lythenas** [comment]
For the moment I only added DING. Are there any other extensions we currently know that are not working.

**Comment by jtaala** [comment]
Thanks @Lythenas,

Yep, definitely one here: https://github.com/paperwm/PaperWM/issues/763

Pretty much any rounded-corner extensions doesn't work/play nice with PaperWM.

**Comment by jtaala** [comment]
Here's a few more too that might(?) be worth mentioning:

https://github.com/paperwm/PaperWM/issues?q=is%3Aissue+is%3Aopen+label%3Aextension-conflict

**Comment by Lythenas** [comment]
Thank you, I didn't think to check that issue label. I added some more extensions to the list.

**Review by jtaala — APPROVED** [review]

**Pull request merged**
