### PR TITLE
Update README.md to explain where settings are

### PR DESCRIPTION
**Pull request by pjsxw**
As a new user, it took a bit of googling to figure out where to find GNOME extension settings. This PR adds a hint to the README for that.

### CODE REVIEW

**Review by Lythenas — COMMENTED** [review]
Thanks for the addition.

I would maybe say "Extensions app" instead of just extensions to be even more clear.

Btw. I usually access the settings by right clicking the workspace name on the top left and clicking "Workspace preference".

**Comment by AndrewKvalheim** [comment]
It’s never actually called “Extensions app” anywhere though. Maybe make it a link?

> [Extensions](https://apps.gnome.org/Extensions/) → PaperWM → ⋮ → Settings

**Comment by Lythenas** [comment]
yeah, maybe `"Extensions" app` is better. It should just be clear where the _entrypoint_ of that chain is. (an app instead of some menu in e.g. the gnome settings). Maybe I'm overthinking this :smile: 

Adding the link is fine, although I would expect that this is installed by default.

**Comment by jtaala** [comment]
Hey @pjsxw, looks good.  Were you going to add a link for the `Extensions` (is a good idea).

Add the link and we can approve/merge in.

**Comment by pjsxw** [comment]
Yeah, adding a link makes it clearer what is being referred too. Have updated

**Pull request merged**
