### PR TITLE
Ease scratch windows when centering horizontally

### PR DESCRIPTION
**Pull request by glupi-borna**
I was poking around the code and found the `easeScratch` function, which looked to me like it could be used to implement #911. I'm not sure if this is the right function to call because it's used only in one other place (in `makeScratch`), but it seems to work fine at first glance -- though I don't know if there are edge cases to consider.

### CODE REVIEW

**Comment by jtaala** [comment]
Nice one @glupi-borna.  

You're on the right track!  Although that method/approach is a little old and over-complicated (but doing what we want).

Let's update those methods in your branch and get you to test.

Jay.

**Comment by glupi-borna** [comment]
What an absolute ninja! :D
I'll give it a whirl ASAP!

**Comment by jtaala** [comment]
So, I was thinking of having it also center vertically as well (which kind of makes sense for scratch windows).

**Comment by jtaala** [comment]
> So, I was thinking of having it also center vertically as well (which kind of makes sense for scratch windows).

Eh, maybe just do this with #912 (e.g. add an extra shortcut).

**Comment by glupi-borna** [comment]
Yup, I was actually investigating #912 when I noticed `easeSearch`. I can't believe you already got it done! You're super fast.

**Pull request merged**
