### PR TITLE
Workspaces: move hiding of appmenu to _initWorkspaceSequence. fixes #210

### LINKED ISSUE #210: sequential workspace navigation does not update app title in status bar
@hedning when I am switching between workspaces sequentially the selected window title does not appear in the status bar. Planning to look into it later but if have a hint let me know.

### PR DESCRIPTION
**Pull request by goodwillcoding**

### CODE REVIEW

**Comment by goodwillcoding** [comment]
fixes #211

**Comment by goodwillcoding** [comment]
fix for #210

**Comment by hedning** [comment]
Cheers. We're probably going to change the development branch to `development` and let `master` be a stable branch (the arch package already pulls from master, so that seemed easier). Will merge soon.

**Comment by hedning** [comment]
merged to develop in 3b011e3387247dfa33e4df07752a5a130b5fd370

**Pull request closed without merging**
