### PR TITLE
Fix for touch window drag-and-drop

### LINKED ISSUE #735: Window drag-and-drop does not work when started from touchscreen
**Describe the bug**
~~When I try to move a window by its titlebar with the touch screen, the entire tiling view becomes stuck, and going back to the mouse reveals the window "stuck" to the mouse.~~

As of GNOME 46, drag-and-drop doesn't move the tiling hint and the window doesn't land where it should.

Finishing the drag and drop with the mouse then breaks the three-finger trackpad gesture and I have to use the touch scroll gesture to restore normal behavior

**To Reproduce**
1. Tap and hold the titlebar of a tiled window with a touchscreen
2. Move the mouse cursor using a mouse or touchpad

**Expected behavior**
The window follows my finger just as it would the mouse.

**Screenshots**

**Additional context**
Scratch windows do not exhibit this behavior whatsoever.

### PR DESCRIPTION
**Pull request by Thesola10**
This fixes #735

### CODE REVIEW

**Comment by Thesola10** [comment]
Right now the window dragging works with this PR, but tiling scroll still gets stuck afterwards. Not sure what causes that.

**Comment by Thesola10** [comment]
Okay, this is weird. In my nested Shell, touch event coordinates match the global pointer exactly, but on my host Wayland session, it doesn't, which breaks everything.

**Comment by Thesola10** [comment]
Okay, we may need to tell the stage to intercept all touch events to extract a facsimile of `global.get_pointer()`, and somehow do so right as `MoveGrab` is instantiated, even though it's an inherently async opeartion.

Most likely this means creating a broker object between `global.get_pointer()` and our stage-based approach, which is itself involved in (or passed to) the `MoveGrab` instance.

**Comment by Thesola10** [comment]
Pending merge of #751 to rebase before implementing touch handlers

**Comment by Thesola10** [comment]
Actually, disregard the last commit message, any one event also "unlocks" the drag-and-drop event, so this is a reasonable fix -- at least it removes the softlock situation.

**Review by jtaala — COMMENTED** [review]
Hey @Thesola10,

Looks good.  I made a couple of small changes - mainly just a little linting/cleanup, and switched to using PaperWM's `warpPointer` util method (and improved it to made ripple animation showing optional).

Happy to approve this if you're happy with the changes.

**Comment by Thesola10** [comment]
yep, looks good to me!

**Pull request merged**
