### PR TITLE
Improve overview with multi-monitors and add monitor workspace "swap" keybinds

### LINKED ISSUE #310: Make workspaces swappable
Right now, you cannot switch to a workspace that is active on another monitor.
It would be nice to be able to do that, resulting in the swapping of the two workspaces.

### LINKED ISSUE #587: Add several shortcuts to ease working with multiple monitors and PaperWM workspaces
Referencing a few comments here for implementation:

- https://github.com/paperwm/PaperWM/pull/577#issuecomment-1684968422
  - > What about, as a workaround, a way to move a workspace to a different monitor? Or swap two workspaces between monitors. So for now we don't worry about whether we sometimes get mixed up and put the wrong workspaces on the wrong monitors, because the user can fairly easily get them back where they belong. Maybe a shortcut, with no default keybinding.
- https://github.com/paperwm/PaperWM/pull/577#issuecomment-1688046344
  - > After using this with dynamic workspaces for a few days now, I think it really needs a shortcut to inject/insert a new workspace to the right of the current workspace (basically do what happens when you drag a window in overview between two of the workspace thumbnails in overview).

### PR DESCRIPTION
**Pull request by jtaala**
This PR improves overview when using multiple monitors.  

Note, PaperWM works on a per-monitor workspace paradigm (e.g. multi-monitors each will show a different PaperWM space), whereas Gnome works on a  "big workspace across monitors" paradigm. 

Because of this, with multi-monitors, overview can be a little confusing (not too much we can do here until Gnome supports per monitor workspaces).  The changes here improve the situation a little, by:

- ensuring all windows in a space are shown on that space's overview (previously, any windows outside of tiling view where shown on a different monitor - even though the space wasn't on that monitor);
- if needed, warps the pointer to the correct space after overview ends;

It also adds keybinds to swap workspaces on the current monitor with monitors to the left, right, above, and below:

Screenshot from 2023-08-29 23-15-11

It also improves pointer warping by:
- maintaining pointer position - i.e. maintains the pointer position on the switched-to monitor (previously it always warped pointer to the center of the target monitor);
- on warping to a new monitor, will 'ripple' animate at the pointer position (on the new monitor);

### CODE REVIEW

**Comment by jtaala** [comment]
Hey @YaLTeR & @smichel17.

You might be interested in this PR as it implements monitor workspace "swap" keybinds (which swap workspaces with another monitor).

**Comment by YaLTeR** [comment]
Ooh, this is cool, I'm going to try this.

> ensuring all windows in a space are shown on that space's overview (previously, any windows outside of tiling view where shown on a different monitor - even though the space wasn't on that monitor);

Does it by any chance also fix the issue where windows to the edge of one monitor logically overlap the monitor that they would overlap if they weren't clipped by Paper? I.e. if the first monitor has 100% scale and the second monitor has 200% scale, the windows on the first monitor would get rendered at 200% scale despite them being clipped to the first monitor.

**Comment by jtaala** [comment]
> Does it by any chance also fix the issue where windows to the edge of one monitor logically overlap the monitor that they would overlap if they weren't clipped by Paper?

I don't think so - not intentionally anyway.  I don't think I've done the diff scaling thing with monitors.

**Comment by YaLTeR** [comment]
As far as I know, to pick the scale, mutter checks which monitors the window overlaps, and picks the highest monitor scale among them. So maybe this overlap check was corrected as part of this MR, not sure.

**Comment by jtaala** [comment]
> So maybe this overlap check was corrected as part of this MR, not sure

I don't think it will fix it then - all I'm doing here is defining which window actors get shown on a space in overview.

We'd prob have to address/override the logic mutter uses for selecting window scale to fix that one.

**Comment by jtaala** [comment]
P.S. I really like the swapping workspaces on monitors thing - I can't stop playing with it now.

**Comment by matrixes** [comment]
If this is anything similar to the experimental(?) implementation mentioned here https://github.com/paperwm/PaperWM/issues/280#issuecomment-605387839 I'm going to be very happy. Currently I can't seem to get the `moveSpaceToMonitor` config to work, and if this now has a chance of getting more solid support in PaperWM I'm going to have a much easier time reordering my workspaces. They often get reordered when connecting external monitors to my laptop, and without the ability to easily move them around it becomes cumbersome.

**Comment by jtaala** [comment]
> If this is anything similar to the experimental(?) implementation mentioned here [#280 (comment)](https://github.com/paperwm/PaperWM/issues/280#issuecomment-605387839)

I've never tried the experimental shortcuts so can't comment on them.  But these shortcuts swap workspaces between monitors.

> They often get reordered when connecting external monitors to my laptop.

What commit are you on?  Recently merged changes should fix this (or make it much lesson common).

**Comment by jtaala** [comment]
> without the ability to easily move them around

Why don't you just workspace stack switch? (see this comment for a video of how) https://github.com/paperwm/PaperWM/issues/571#issuecomment-1671623560

**Comment by matrixes** [comment]
> > without the ability to easily move them around
> 
> Why don't you just workspace stack switch? (see this comment for a video of how) [#571 (comment)](https://github.com/paperwm/PaperWM/issues/571#issuecomment-1671623560)

In my case it's much faster moving workspaces left/right/up/down than stack switching. All workspaces show up just fine when connecting my monitors, my issue is that the location of each workspace often gets mixed up. When I had `moveSpaceToMonitor` enabled, I could very quickly rearrange the workspaces to put them where I wanted them with arrow keys.
Of course, I would appreciate even more if the workspace arrangement was remembered based on what screens I connected, but keyboard based switching with arrow keys still works.

**Comment by jtaala** [comment]
> In my case it's much faster moving workspaces left/right/up/down than stack switching

Makes sense.

> if the workspace arrangement was remembered based on what screens I connected.

There is now some persistence now and saving of workspace-to-monitor info - but mainly for lock/unlock cycles.

Feel free to checkout this branch and logout/login again:

```
git fetch --all
git checkout improve-multimonitor-overview
```
The logout/login and test out the keyboard shortcuts.

**Comment by jtaala** [comment]
Looking at merging into `develop` shortly and then it will make it's way to `release`.

**Comment by jtaala** [comment]
@matrixes it's now in `develop` and `release` branches.

**Comment by jtaala** [comment]
> When I had `moveSpaceToMonitor` enabled

Let me know what you think of the swapping workspace behaviour.

I'd be happy to add official support for `moveSpaceToMonitor` if swapping isn't quite the right behaviour to quickly move workspaces around.

Also see https://github.com/paperwm/PaperWM/issues/206#issuecomment-1698998753

**Comment by matrixes** [comment]
> > When I had `moveSpaceToMonitor` enabled
> 
> Let me know what you think of the swapping workspace behaviour.
> 
> I'd be happy to add official support for `moveSpaceToMonitor` if swapping isn't quite the right behaviour to quickly move workspaces around.
> 
> Also see [#206 (comment)](https://github.com/paperwm/PaperWM/issues/206#issuecomment-1698998753)

Initial impression from the changes deployed from this merge are good. I haven't tested extensively (it's only been an hour or two after all), but so far I the current implementation looks perfectly sufficient for my needs. I highly appreciate the efforts put into this!

**Comment by jtaala** [comment]
Hey all, had to temporarily disable the `swap` monitor keybinds in develop/release branches due users reporting #591.  Seems gnome or PaperWM treats Super+Alt+left/right the same as Super+page_up/page_down.

Will re-enable this feature once I can look at that issue.

**Comment by yongweiy** [comment]
Workspace swap works smoothly for me. Thank you @jtaala for making it happen!

> I'd be happy to add official support for `moveSpaceToMonitor` if swapping isn't quite the right behaviour to quickly move workspaces around.

I may be biased but would love to have the `moveSpaceToMonitor` behavior as it makes workspace arrangement more flexible. With only swapping, the number of workspace on a monitor is essentially fixed. Personally, I have a smaller monitor dedicated for one workspace where I keep all messaging apps.

**Comment by jtaala** [comment]
> Workspace swap works smoothly for me. Thank you @jtaala for making it happen!
> 
> > I'd be happy to add official support for `moveSpaceToMonitor` if swapping isn't quite the right behaviour to quickly move workspaces around.
> 
> I may be biased but would love to have the `moveSpaceToMonitor` behavior as it makes workspace arrangement more flexible. With only swapping, the number of workspace on a monitor is essentially fixed. Personally, I have a smaller monitor dedicated for one workspace where I keep all messaging apps.

Hey @VictorYYW - I added this (or something similar) in #825, give that one a go:

image

**Comment by yongweiy** [comment]
That's awesome - I didn't know it is already implemented. Thanks again for another awesome work!

**Pull request merged**
